### ISSUE TITLE
Please add a feed

### ISSUE THREAD

**Issue by moltar** [astuyve/astuyve.github.io#31]
Hey AJ,

I enjoyed reading your Lambda streaming post. I am also into serverless and always trying to subscribe to the people I enjoy reading. But I noticed that your site lacks a feed.

I think Jekyll has an easy option for adding a feed, even tho I had never used it myself.

https://github.com/jekyll/jekyll-feed

Cheers!

**Comment by astuyve** [comment]
Hey @moltar - it's so kind of you to reach out! I'm quite pleased you opened an issue for this, and I'm sorry I missed this in my (admittedly dumpster-fire) github notifications.

Absolutely, I'll resolve this issue when I get a feed set up.

Best!
AJ

**Comment by astuyve** [comment]
Done! The feed is now available at https://aaronstuyvenberg.com/feed

**Comment by moltar** [comment]
Awesome, I'm a subscriber now :) Looking forward to more posts!
